spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /auth/v3/api-docs/**
          filters:
            - StripPrefix=0
            - RewritePath=/auth/v3/api-docs(?<segment>.*), /v3/api-docs${segment}

        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/policy/**, /policy/v3/api-docs/**
          filters:
            - StripPrefix=0
            - RewritePath=/policy/v3/api-docs(?<segment>.*), /v3/api-docs${segment}

        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/claim/**, /claim/v3/api-docs/**
          filters:
            - StripPrefix=0
            - RewritePath=/claim/v3/api-docs(?<segment>.*), /v3/api-docs${segment}

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**, /admin/v3/api-docs/**
          filters:
            - StripPrefix=0
            - RewritePath=/admin/v3/api-docs(?<segment>.*), /v3/api-docs${segment}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urlsPrimaryName: AUTH SERVICE
    urls:
      - name: AUTH SERVICE
        url: /auth/v3/api-docs
      - name: POLICY SERVICE
        url: /policy/v3/api-docs
      - name: CLAIM SERVICE
        url: /claim/v3/api-docs
      - name: ADMIN SERVICE
        url: /admin/v3/api-docs
